version: '3'

services:
  app:
    build: .
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "5000:5000"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
